version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./mobile-foodprovider-spa
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

